FROM node:lts-alpine AS builder
WORKDIR /app

COPY ./worklog-frontend/package*.json ./
RUN npm install

COPY ./worklog-frontend ./
RUN npm run build

FROM nginx:alpine

COPY --from=builder /app/dist /usr/share/nginx/html

COPY ./worklog-frontend/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]
